In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv('iris1.csv')
data.head()

Sepal_Length   Sepal_Width   Petal_Length   Petal_Width        Class
0           5.1           3.5            1.4           0.2  Iris-setosa
1           4.9           3.0            1.4           0.2  Iris-setosa
2           4.7           3.2            1.3           0.2  Iris-setosa
3           4.6           3.1            1.5           0.2  Iris-setosa
4           5.0           3.6            1.4           0.2  Iris-setosa

In [23]:
x = data.drop(['Class'],axis=1)
y = data['Class']

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [25]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train,y_train)
ypred = model.predict(x_test)

In [26]:
newData = [[2, 1, 0, 0]]
predict = model.predict(newData)
print(predict)

['Iris-setosa']


C:\Users\adity\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


In [27]:
from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y_test, ypred)
print("Confusion Matrix we want is: \n", conf)

Confusion Matrix we want is: 
 [[11  0  0]
 [ 0  0 13]
 [ 0  0  6]]


In [28]:
from sklearn.metrics import f1_score, precision_score, recall_score, matthews_corrcoef,accuracy_score
print(f"Recall Score: {recall_score(y_test, ypred,average='micro'):.3}")
print(f"Precision Score: {precision_score(y_test, ypred,average='micro'):.3}")
print(f"F1 Score: {f1_score(y_test, ypred,average='micro'):.3}")
print(f"Matthews Correlation Coefficient: {matthews_corrcoef(y_test, ypred):.3}")
print(f"Accuracy Score: {accuracy_score(y_test, ypred):.3}")

Recall Score: 0.567
Precision Score: 0.567
F1 Score: 0.567
Matthews Correlation Coefficient: 0.561
Accuracy Score: 0.567
