In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv('balance-scale.csv')
data.head()

B  1  1.1  1.2  1.3
0  R  1    1    1    2
1  R  1    1    1    3
2  R  1    1    1    4
3  R  1    1    1    5
4  R  1    1    2    1

In [30]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=0)

In [31]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(xtrain,ytrain)
ypred = model.predict(xtest)

In [32]:
newData = [[1, 1, 1, 1]]
predict = model.predict(newData)
print(predict)

['R']


C:\Users\adity\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


In [33]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,ypred)
print(cm)

[[ 0  0  8]
 [ 0 55  7]
 [ 0  0 55]]


In [34]:
from sklearn.metrics import f1_score, precision_score, recall_score, matthews_corrcoef, accuracy_score
print(f"Recall Score: {recall_score(ytest, ypred,average='micro'):.3}")
print(f"Precision Score: {precision_score(ytest, ypred,average='micro'):.3}")
print(f"F1 Score: {f1_score(ytest, ypred,average='micro'):.3}")
print(f"Matthews Correlation Coefficient: {matthews_corrcoef(ytest, ypred):.3}")
print(f"Accuracy Score: {accuracy_score(ytest, ypred):.3}")


Recall Score: 0.88
Precision Score: 0.88
F1 Score: 0.88
Matthews Correlation Coefficient: 0.793
Accuracy Score: 0.88


In [36]:
# from sklearn.metrics import auc, roc_curve
# fpr, tpr, thresholds = roc_curve(ytest, ypred)
# area = auc(fpr, tpr)
# print(f"Area Under Curve: {area:.3}")
# plt.plot(fpr, tpr)

ValueError: multiclass format is not supported